In [2]:
import numpy as np
import cv2
test_video_new = np.load('west_video.npy_new1.npy')
print(test_video_new[0])
test_video_new.shape
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('west_new.avi',fourcc, 10.0, (720,1280))
for i in range(len(test_video_new)):
   frame = test_video_new[i]
   out.write(frame)
out.release()

[[[222 213 192]
  [222 213 192]
  [221 212 191]
  ..., 
  [184 186 193]
  [162 164 171]
  [139 141 148]]

 [[222 213 192]
  [222 213 192]
  [221 212 191]
  ..., 
  [189 191 198]
  [166 168 175]
  [142 144 151]]

 [[223 214 193]
  [223 214 193]
  [223 214 193]
  ..., 
  [196 198 205]
  [174 176 183]
  [151 153 160]]

 ..., 
 [[150 149 206]
  [154 153 210]
  [159 158 215]
  ..., 
  [ 70  75  86]
  [ 67  72  83]
  [ 66  71  82]]

 [[148 147 204]
  [151 150 207]
  [157 156 213]
  ..., 
  [ 81  86  97]
  [ 78  83  94]
  [ 77  82  93]]

 [[148 147 204]
  [151 150 207]
  [157 156 213]
  ..., 
  [ 86  91 102]
  [ 84  89 100]
  [ 82  87  98]]]
